# Generated by Django 4.2.3 on 2023-08-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_banner_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='servis',
            name='img',
            field=models.ImageField(default=1, upload_to='Servis/'),
            preserve_default=False,
        ),
    ]
